version: "3"
services:
  app:
    image: brutalhz/datachain-demo
    networks:
      - mynet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
