name: CI-CD
on:
  push:
    branches: [main]


jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

        # install applicaion dependencies
      - name: Install dependencies
        run: |
           npm cache clean --force
           npm i --force

      - name: build
        run: |
          npm run build

  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    needs: [build_test]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REACTUSERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REACTUSERNAME }}/datachain-demo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [push_to_Docker_Hub]

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          mkdir ../app
          cp docker-compose.yml ../app
          cp nginx/app.conf ../app
          tar -cvf deploy.tar ../app

       # Copy docker-compose and .env files to target server
      - name: copy files to target server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.YC_HOST }}
          username: ${{ secrets.YC_USERNAME }}
          port: 22
          key: ${{ secrets.YC_PRIVATE_KEY }}
          source: "deploy.tar"
          target: ${{ secrets.TARGET }}
#          strip_components: 1
#
      - name: Deploy to vps via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YC_HOST }}
          username: ${{ secrets.YC_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.YC_PRIVATE_KEY }}
          script: |
            tar -xf deploy.tar
            cd app/
            docker system prune -af
            docker compose down
            docker login -u ${{ secrets.REACTUSERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker compose pull
            docker compose up -p my_demo --remove-orphans -d --force-recreate
